In [19]:
import pandas as pd
import numpy as np
import datetime

In [20]:
df= pd.read_excel("F:\Data\Liquidity.xlsx")

In [21]:
df.head()

  Ticker  Date/Time  Open  High   Low  Close  Quantity
0    A32 2019-07-26  23.1  23.1  23.1   23.1       100
1    A32 2019-07-29  24.0  24.0  24.0   24.0       100
2    A32 2019-07-30  24.0  24.0  24.0   24.0        33
3    A32 2019-07-31  23.5  23.5  23.5   23.5       200
4    A32 2019-08-01  24.0  24.0  24.0   24.0       400

In [22]:
def remove_outlier(df_in, col_name):
    q1 = df_in[col_name].quantile(0.25)
    q3 = df_in[col_name].quantile(0.75)
    iqr = q3-q1 #Interquartile range
    fence_low  = q1-1.5*iqr
    fence_high = q3+1.5*iqr
    df_out = df_in.loc[(df_in[col_name] > fence_low) & (df_in[col_name]< fence_high)]
    return df_out

In [23]:
my_set = set(df["Ticker"])
my_set

{'NTB',
 'C36',
 'POT',
 'BLI',
 'CKV',
 'MSH',
 'TAC',
 'THG',
 'SVI',
 'UDC',
 'LIG',
 'CLH',
 'NVB',
 'LM7',
 'S55',
 'PGS',
 'FIR',
 'HLG',
 'HU6',
 'TYA',
 'SGN',
 'MHC',
 'SMN',
 'DRL',
 'CTS',
 'REE',
 'ITQ',
 'STK',
 'NBT',
 'TCT',
 'NCP',
 'SFN',
 'NDT',
 'IFC',
 'PME',
 'TDM',
 'TSJ',
 'SHP',
 'BAL',
 'SJE',
 'ITC',
 'GDW',
 'LDP',
 'ASP',
 'SCC',
 'BLF',
 'DAP',
 'BT6',
 'HAN',
 'LWS',
 'ATB',
 'FUCVREIT',
 'TOT',
 'VIF',
 'MIC',
 'THT',
 'HPP',
 'NNT',
 'PSW',
 'CLW',
 'PVC',
 'WTC',
 'NSL',
 'VJC',
 'MFS',
 'BTV',
 'V12',
 'TVT',
 'PTB',
 'SEP',
 'API',
 'CDC',
 'DBC',
 'IDC',
 'CID',
 'L14',
 'GAS',
 'S99',
 'HRB',
 'CAV',
 'ITA',
 'TV2',
 'DTG',
 'VBB',
 'BSA',
 'GTN',
 'VIP',
 'MKV',
 'DNY',
 'SJF',
 'TIP',
 'UDJ',
 'TV1',
 'HU1',
 'DSV',
 'CTI',
 'TCD',
 'TSD',
 'LTG',
 'LM3',
 'GND',
 'CMD',
 'EVS',
 'TTH',
 'NS3',
 'BMD',
 'SBL',
 'PVY',
 'CHS',
 'HU4',
 'GTS',
 'VGG',
 'BAX',
 'BSR',
 'VSF',
 'SGS',
 'DHN',
 'CCP',
 'DBD',
 'NLS',
 'ATS',
 'SGR',
 'BLT',
 'AVF',
 'CFPT1904',
 'MAS',
 'ACE',
 'LKW',
 'THS',
 'TNI',
 'HWS',
 'T12',
 'VTV',
 'TMP',
 'QPH',
 'VIW',
 'BCM',
 'CCL',
 'MTA',
 'PVE',
 'CFPT1902',
 'FOC',
 'KSK',
 'PNP',
 'MCH',
 'VSH',
 'HHC',
 'CGV',
 'TPB',
 'V11',
 'MCF',
 'MSN',
 'IPA',
 'UNI',
 'HMC',
 'VDT',
 'LPB',
 'POW',
 'CMS',
 'FCM',
 'CQT',
 'PIA',
 'VHG',
 'SCS',
 'HAI',
 'ND2',
 'PBT',
 'HNM',
 'SBH',
 'PEQ',
 'ONE',
 'DP1',
 'MST',
 'DST',
 'SDH',
 'CSM',
 'PWS',
 'CRE',
 'TBC',
 'DHT',
 'STP',
 'NSG',
 'DRC',
 'PIT',
 'FTM',
 'ISH',
 'HJS',
 'VNE',
 'VSM',
 'QHD',
 'ILB',
 'MSR',
 'PPE',
 'KSD',
 'VCX',
 'HDM',
 'MHL',
 'TA6',
 'BVH',
 'MTP',
 'VEC',
 'DAT',
 'SJM',
 'CTR',
 'VIB',
 'SDJ',
 'LIX',
 'CTC',
 'HCM',
 'BCP',
 'CSC',
 'TVH',
 'CC4',
 'CMN',
 'TEL',
 'FID',
 'CHPG1905',
 'BSQ',
 'HLC',
 'SDB',
 'BSG',
 'SHI',
 'TL4',
 'MVB',
 'BID',
 'FSO',
 'CMWG1904',
 'TLI',
 'BMJ',
 'TVC',
 'THB',
 'PVA',
 'SPM',
 'VIG',
 'CBI',
 'VCI',
 'VRG',
 'GKM',
 'VGV',
 'PVG',
 'SBM',
 'HEJ',
 'VGT',
 'SKN',
 'DNE',
 'KHB',
 'TLD',
 'SZC',
 'HHS',
 'DRH',
 'TV3',
 'ALT',
 'HPD',
 'AMC',
 'TBD',
 'HIG',
 'NPS',
 'VNB',
 'VPA',
 'BBS',
 'EMS',
 'HMH',
 'VC2',
 'DNC',
 'MGG',
 'SDT',
 'NDN',
 'PHH',
 'TLG',
 'HNX-INDEX',
 'DFS',
 'FUCTVGF1',
 'KIP',
 'SWC',
 'TBX',
 'HLS',
 'SB1',
 'VTC',
 'DRI',
 'C21',
 'VT8',
 'DBT',
 'SCL',
 'CAT',
 'HCS',
 'CX8',
 'GMC',
 'COM',
 'VC6',
 'STL',
 'TMS',
 'TTV',
 'STG',
 'RTS',
 'SAV',
 'TLT',
 'VMS',
 'BWS',
 'MCG',
 'RGC',
 'BCE',
 'HTE',
 'DNM',
 'TJC',
 'EVF',
 'PGC',
 'CDN',
 'BLW',
 'PHR',
 'DXG',
 'TIE',
 'TNT',
 'HTP',
 'ANV',
 'IN4',
 'CVHM1901',
 'SIG',
 'EID',
 'VNA',
 'SBD',
 'EVE',
 'STT',
 'MCT',
 'PJC',
 'VPD',
 'HHA',
 'PGI',
 'PMC',
 'VNINDEX',
 'MVY',
 'BCG',
 'HAF',
 'TQN',
 'MCP',
 'PCG',
 'VAV',
 'PFL',
 'SCD',
 'RTB',
 'EIN',
 'DNL',
 'LBM',
 'TTF',
 'NED',
 'HEP',
 'KHA',
 'SCJ',
 'BVN',
 'ICC',
 'NTL',
 'FDC',
 'HCD',
 'TIG',
 'BPC',
 'AGM',
 'DTL',
 'SBV',
 'IMP',
 'DTV',
 'XMC',
 'CMSN1901',
 'IST',
 'PDV',
 'TCO',
 'CNC',
 'MEC',
 'ACV',
 'KHL',
 'DL1',
 'PPH',
 'QNS',
 'LO5',
 'HDP',
 'GLW',
 'CMWG1902',
 'QHW',
 'VIM',
 'CMW',
 'DSP',
 'AGR',
 'BSH',
 'VDL',
 'KDM',
 'PXM',
 'BVS',
 'PVI',
 'DPR',
 'CLX',
 'EMC',
 'VBH',
 'BEL',
 'VC9',
 'VCP',
 'HFC',
 'VSG',
 'CNN',
 'SRF',
 'VBC',
 'ST8',
 'HEC',
 'EVG',
 'GGS',
 'EFI',
 'BSL',
 'GLT',
 'APS',
 'SJG',
 'L12',
 'MVC',
 'NAP',
 'PSB',
 'VSI',
 'PSN',
 'SBS',
 'HPW',
 'PLP',
 'VGP',
 'BGW',
 'HBS',
 'KLF',
 'AMV',
 'TDW',
 'IDI',
 'PTD',
 'L18',
 'BIC',
 'MDC',
 'NBW',
 'OIL',
 'ALV',
 'CLG',
 'EME',
 'CI5',
 'VDS',
 'SPB',
 'HBD',
 'MCO',
 'FTS',
 'DCL',
 'SCR',
 'VGS',
 'VFC',
 'VHE',
 'HAM',
 'C4G',
 'FUCTVGF2',
 'PCE',
 'SSC',
 'STV',
 'CDH',
 'MBG',
 'TTB',
 'TDT',
 'CMBB1903',
 'TV4',
 'HRC',
 'TMW',
 'ANT',
 'D11',
 'KSH',
 'VCF',
 'DID',
 'PNJ',
 'XPH',
 'IME',
 'SFC',
 'DAG',
 'TLH',
 'CC1',
 'BKC',
 'PEN',
 'VC7',
 'QTC',
 'HPI',
 'DNA',
 'HTT',
 'KTS',
 'SHB',
 'SRC',
 'BTD',
 'PTL',
 'PDR',
 'CHPG1904',
 'GEG',
 'CMWG1907',
 'PVV',
 'CH5',
 'HUT',
 'GIL',
 'HPB',
 'AAV',
 'HNT',
 'BBT',
 'TSG',
 'VMC',
 'SJ1',
 'HSA',
 'HKT',
 'DPM',
 'PAN',
 'BSI',
 'VID',
 'MVN',
 'STC',
 'ATA',
 'L63',
 'GDT',
 'DBM',
 'VPS',
 'TTE',
 'HNF',
 'GEX',
 'HPT',
 'MQN',
 'TVB',
 'OGC',
 'TA9',
 'KCB',
 'GSP',
 'NDX',
 'DCD',
 'CVN',
 'BDC',
 'ABC',
 'PSE',
 'VCG',
 'CTF',
 'KSQ',
 'BTN',
 'HUG',
 'BMC',
 'DXV',
 'VEF',
 'RCD',
 'UPC',
 'L61',
 'VTO',
 'SD2',
 'TNW',
 'TIS',
 'BDP',
 'VQC',
 'NCS',
 'VNC',
 'VWS',
 'SHE',
 'VNT',
 'GSM',
 'VPI',
 'DVP',
 'CMC',
 'SKV',
 'VGL',
 'PSD',
 'PVD',
 'TDN',
 'VE1',
 'HTI',
 'ELC',
 'APC',
 'EBS',
 'V15',
 'YEG',
 'SAM',
 'NOS',
 'DP2',
 'VCA',
 'MTG',
 'HDO',
 'ADP',
 'CPC',
 'HLD',
 'STB',
 'VCW',
 'VNAll-INDEX',
 'BUD',
 'PSC',
 'SHA',
 'SDA',
 'ICN',
 'HTR',
 'QCG',
 'BTT',
 'QCC',
 'TCW',
 'PPS',
 'DPS',
 'TNG',
 'VFR',
 'HCT',
 'NBB',
 'S12',
 'TW3',
 'LHC',
 'HPM',
 'DIG',
 'PMJ',
 'VNR',
 'NHA',
 'SDN',
 'POM',
 'NAV',
 'C12',
 'ABR',
 'CVIC1902',
 'TTZ',
 'SDP',
 'TMC',
 'LMC',
 'TKU',
 'DCS',
 'HBC',
 'KOS',
 'DHD',
 'DTC',
 'CCM',
 'CDO',
 'CNVL1901',
 'SD8',
 'VMG',
 'AMP',
 'CVRE1902',
 'LHG',
 'FGL',
 'SAS',
 'CREE1901',
 'HTC',
 'BRC',
 'KMT',
 'APT',
 'HSM',
 'TTT',
 'CRC',
 'CPW',
 'TN1',
 'HNA',
 'ABI',
 'ACM',
 'HTM',
 'PVX',
 'PTI',
 'PGN',
 'SDI',
 'SMT',
 'SHC',
 'PVO',
 'GHC',
 'S4A',
 'IFS',
 'SAB',
 'LEC',
 'AFC',
 'FPT',
 'OPC',
 'SPV',
 'L35',
 'QLD',
 'CMBB1902',
 'APF',
 'AME',
 'HAD',
 'SHN',
 'INC',
 'SD7',
 'SBT',
 'BTB',
 'TAG',
 'AMD',
 'CTG',
 'TTJ',
 'VND',
 'RAT',
 'SKH',
 'ASM',
 'HLY',
 'TVM',
 'DIH',
 'PXA',
 'SHS',
 'VTP',
 'A32',
 'DLG',
 'LDW',
 'DAE',
 'C92',
 'ICG',
 'AGP',
 'TIX',
 'BPW',
 'C32',
 'WSB',
 'PMG',
 'VNH',
 'SCI',
 'VMD',
 'CFPT1901',
 'DPP',
 'HAR',
 'GVT',
 'TVD',
 'FCN',
 'VNS',
 'VTH',
 'MPC',
 'TAP',
 'CTP',
 'FRC',
 'PVH',
 'LLM',
 'PMS',
 'G20',
 'PIC',
 'PTP',
 'IHK',
 'CKD',
 'CREE1902',
 'KCE',
 'BMP',
 'QSP',
 'DIC',
 'PCM',
 'PHN',
 'VE8',
 'HIZ',
 'CHPG1907',
 'PVM',
 'BMS',
 'VTR',
 'HTL',
 'HAH',
 'LGC',
 'KST',
 'AGX',
 'VCB',
 'HVG',
 'DTI',
 'TDG',
 'FRT',
 'CPNJ1901',
 'HLA',
 'PSI',
 'PRO',
 'CMT',
 'ART',
 'DVN',
 'GMD',
 'HNI',
 'VES',
 'LBC',
 'BHC',
 'PIS',
 'PMT',
 'QLT',
 'IJC',
 'DHG',
 'NAS',
 'SVN',
 'PBP',
 'CAP',
 'LMH',
 'DSC',
 'NS2',
 'TDB',
 'VE2',
 'KHS',
 'DVW',
 'NT2',
 'BTW',
 'DFC',
 'LAW',
 'PKR',
 'CGP',
 'LIC',
 'SDU',
 'CFC',
 'LTC',
 'VPB',
 'VTL',
 'NDC',
 'NDP',
 'NFC',
 'ACC',
 'SOV',
 'SD4',
 'SEA',
 'TSB',
 'HES',
 'HVX',
 'CVT',
 'HAV',
 'HAC',
 'PNC',
 'PEC',
 'VIX',
 'DNR',
 'HNG',
 'DHC',
 'SSF',
 'DGT',
 'CTN',
 'TDS',
 'VC5',
 'DGC',
 'PVR',
 'DHA',
 'FT1',
 'CNG',
 'BWA',
 'NST',
 'VLB',
 'NKG',
 'VKC',
 'DMC',
 'NBR',
 'CCI',
 'FIC',
 'BDG',
 'TNB',
 'VLA',
 'TMB',
 'SVC',
 'VPH',
 'SDD',
 'ASA',
 'ACS',
 'HDA',
 'POV',
 'VNX',
 'CET',
 'AST',
 'BBM',
 'PPY',
 'CTB',
 'NBC',
 'HT1',
 'MTH',
 'VLG',
 'POB',
 'VTS',
 'BII',
 'MDF',
 'VC1',
 'BTH',
 'VNF',
 'CAG',
 'DTA',
 'CT3',
 'BKH',
 'HKP',
 'SAF',
 'VIH',
 'NVL',
 'PDT',
 'CIP',
 'HMG',
 'TRS',
 'PHC',
 'VIN',
 'DC4',
 'GTT',
 'SD9',
 'TOW',
 'V21',
 'PTS',
 'LGL',
 'NBP',
 'VRE',
 'DTN',
 'SIC',
 'SED',
 'DGW',
 'SSM',
 'VLW',
 'NCT',
 'HND',
 'ECI',
 'HTK',
 'PVS',
 'FUESSV50',
 'LAF',
 'PXL',
 'FHS',
 'AG1',
 'PTH',
 'CHPG1903',
 'DVC',
 'KBC',
 'TXM',
 'SJC',
 'NHH',
 'DDN',
 'NTW',
 'TAW',
 'CKH',
 'EPH',
 'RIC',
 'HAS',
 'TPS',
 'CAN',
 'PHP',
 'CPI',
 'NRC',
 'PPI',
 'VIS',
 'BED',
 'NTF',
 'MLS',
 'SII',
 'BLN',
 'PVP',
 'C71',
 'SJD',
 'TTC',
 'VXP',
 'DPC',
 'PJT',
 'SPC',
 'CIG',
 'CVJC1901',
 'BHP',
 'VET',
 'HLB',
 'HAT',
 'TDH',
 'PWA',
 'TNP',
 'TCS',
 'KMR',
 'SPI',
 'GVR',
 'SSN',
 'TTN',
 'PVT',
 'DAS',
 'PMW',
 'TC6',
 'KSV',
 'PJS',
 'DPG',
 'HNP',
 'HOM',
 'DCF',
 'SMB',
 'TVA',
 'ONW',
 'KHD',
 'FDT',
 'CEC',
 'PPP',
 'NHC',
 'AAM',
 'VPC',
 'CVHM1902',
 'PVB',
 'RDP',
 'TNS',
 'CSI',
 'TVS',
 'CLC',
 'VC3',
 'CIA',
 'PXI',
 'KDH',
 'VDN',
 'CMWG1905',
 'CNT',
 'HDC',
 'NHT',
 'HAX',
 'ASD',
 'CFPT1905',
 'TPC',
 'IDV',
 'EIB',
 'VAT',
 'PAC',
 'L44',
 'CMBB1901',
 'VNL',
 'VNI',
 'HPG',
 'VT1',
 'AVC',
 'HC3',
 'NLG',
 'VNG',
 'HAP',
 'ATG',
 'L10',
 'HPH',
 'NGC',
 'VCS',
 'ITS',
 'SJS',
 'LUT',
 'TFC',
 'VKD',
 'GMX',
 'S74',
 'ACB',
 ...}

In [24]:
final_df = pd.DataFrame(columns = ["Ticker", "Date/Time", "Open","High","Low","Close","Quantity"])
for r in my_set:
    res_df1 = df[df['Ticker'] == r]
    res_df2 = remove_outlier(res_df1, "Quantity")
    final_df = final_df.append(res_df2)

In [25]:
final_df

      Ticker  Date/Time  Open  High  Low  Close Quantity
29264    NTB 2019-07-26   0.3   0.3  0.3    0.3     5734
29265    NTB 2019-08-02   0.4   0.4  0.3    0.3     6604
29266    NTB 2019-08-09   0.4   0.4  0.3    0.3    98401
29267    NTB 2019-08-16   0.3   0.4  0.3    0.3    98700
29268    NTB 2019-08-23   0.3   0.4  0.3    0.4   288600
...      ...        ...   ...   ...  ...    ...      ...
24558    LAS 2019-10-14   6.9   6.9  6.8    6.8     4230
24561    LAS 2019-10-17   7.0   7.1  7.0    7.0    20500
24563    LAS 2019-10-21   7.0   7.2  7.0    7.1    21310
24564    LAS 2019-10-22   7.0   7.1  6.9    7.0    29200
24565    LAS 2019-10-23   7.0   7.0  6.9    7.0    23600

[48743 rows x 7 columns]

In [26]:
df['month'] = pd.DatetimeIndex(df['Date/Time']).month

In [27]:
month = list(range(13))

In [28]:
duniq = final_df["Date/Time"].dt.strftime('%y-%m-%d')

In [29]:
final_df['month'] = pd.DatetimeIndex(final_df['Date/Time']).month

In [37]:
final_df_2 = pd.DataFrame(columns = ["Ticker", "Date/Time", "Open","High","Low","Close","Quantity", "Average"])
for a in my_set:
    for m in month:
        res_1 = final_df[final_df['Ticker'] == a]
        res_1['month'] = pd.DatetimeIndex(res_1['Date/Time']).month
        res_2 = res_1[res_1['month'] == m]    
        Average = res_2["Quantity"].mean()
        res_2["Average"] = Average
        final_df_2 = final_df_2.append(res_2)
final_df_2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

             Average  Close  Date/Time  High  Low  Open Quantity Ticker  month
29264    5734.000000    0.3 2019-07-26   0.3  0.3   0.3     5734    NTB    7.0
29265  126900.000000    0.3 2019-08-02   0.4  0.3   0.4     6604    NTB    8.0
29266  126900.000000    0.3 2019-08-09   0.4  0.3   0.4    98401    NTB    8.0
29267  126900.000000    0.3 2019-08-16   0.4  0.3   0.3    98700    NTB    8.0
29268  126900.000000    0.4 2019-08-23   0.4  0.3   0.3   288600    NTB    8.0
...              ...    ...        ...   ...  ...   ...      ...    ...    ...
24558   10113.285714    6.8 2019-10-14   6.9  6.8   6.9     4230    LAS   10.0
24561   10113.285714    7.0 2019-10-17   7.1  7.0   7.0    20500    LAS   10.0
24563   10113.285714    7.1 2019-10-21   7.2  7.0   7.0    21310    LAS   10.0
24564   10113.285714    7.0 2019-10-22   7.1  6.9   7.0    29200    LAS   10.0
24565   10113.285714    7.0 2019-10-23   7.0  6.9   7.0    23600    LAS   10.0

[48743 rows x 9 columns]

In [15]:

res_1 = final_df[final_df['Ticker'] == "AAA"]
res_1['month'] = pd.DatetimeIndex(res_1['Date/Time']).month
res_2 = res_1[res_1['month'] == 8]
res_2["Average"] = res_2["Quantity"].mean()
res_3 = res_2.append(res_2["Average"])
res_3 = res_3.reindex(columns = ["Ticker", "Date/Time", "Open","High","Low","Close","Quantity","Average"])
res_3

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

        Ticker  Date/Time   Open   High    Low  Close Quantity       Average
39         AAA 2019-08-01  17.90  18.15  17.70  17.95  3177710  2.061776e+06
40         AAA 2019-08-02  17.90  18.05  17.75  17.85  3410500  2.061776e+06
41         AAA 2019-08-05  17.85  17.90  17.50  17.55  3949330  2.061776e+06
43         AAA 2019-08-07  17.45  17.65  17.45  17.45  2395900  2.061776e+06
44         AAA 2019-08-08  17.50  17.65  17.25  17.50  2482830  2.061776e+06
45         AAA 2019-08-09  17.50  17.75  17.50  17.60  1858000  2.061776e+06
46         AAA 2019-08-12  17.60  17.70  17.35  17.40  1513420  2.061776e+06
47         AAA 2019-08-13  17.35  17.50  17.30  17.40  1718080  2.061776e+06
48         AAA 2019-08-14  17.10  17.40  17.10  17.20  1610620  2.061776e+06
49         AAA 2019-08-15  16.80  17.20  16.80  17.20  1520850  2.061776e+06
50         AAA 2019-08-16  17.20  17.30  17.05  17.05  1329320  2.061776e+06
51         AAA 2019-08-19  17.05  17.30  16.95  16.95   977320  2.061776e+06
52         AAA 2019-08-20  16.95  17.15  16.85  16.85  1504480  2.061776e+06
53         AAA 2019-08-21  16.85  17.05  16.70  16.90  2408380  2.061776e+06
54         AAA 2019-08-22  16.95  17.10  16.90  16.90  1181170  2.061776e+06
55         AAA 2019-08-23  16.90  17.05  16.80  16.95   904360  2.061776e+06
56         AAA 2019-08-26  16.85  16.90  16.30  16.50  2466420  2.061776e+06
57         AAA 2019-08-27  16.55  16.65  16.20  16.25  2401690  2.061776e+06
58         AAA 2019-08-28  16.25  16.40  16.05  16.05  1701810  2.061776e+06
59         AAA 2019-08-29  16.05  16.15  15.80  15.80  2051390  2.061776e+06
60         AAA 2019-08-30  15.90  16.40  15.90  16.40  2733710  2.061776e+06
Average    NaN        NaT    NaN    NaN    NaN    NaN      NaN           NaN

In [16]:
res_3

        Ticker Date/Time  Open  High  Low  Close Quantity  month  Average
Average    NaN       NaT   NaN   NaN  NaN    NaN      NaN    NaN      NaN

In [39]:
final_df_2.to_csv("F:\Data\cleanv2.csv")